logging:
  level:
    org:
      hibernate: info
    root: info
server:
  port: 9000


spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: library
  datasource:
    password: 123456
    url: jdbc:postgresql://localhost:5433/Library
    username: postgres
    hikari:
      maximum-pool-size: 4
  flyway:
    baseline-on-migrate: true
    enabled: true
    locations: classpath:db/schema/
    password: 123456
    schemas: library
    url: jdbc:postgresql://localhost:5433/Library
    user: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: validate
      properties:
        hibernate:
          format_sql: true
          temp:
            use_jdbc_metadata_defaults: false
      show-sql: false
    properties:
      hibernate:
        default_schema: '"library"'
        format_sql: true
        jdbc:
          batch_size: 25
        order_inserts: true
        temp:
          use_jdbc_metadata_defaults: false
      show-sql: false
